# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f263f903dad0b481693538b5f047fe7d30b9f9477c6cccf980fb143dd97556cfaeb202932dd921e7c0ee58de9f88ba1e7772627e44564f84b3f54b2d31df1895

test:
  secret_key_base: 3b1873d1ff9e10a4673287fe63ae5e3418d61b16e2796ee785332fae8f5ac7996ba972238142e281bcff0dd5e24da9fcf07902c2f341d87b58d5508d156d21c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
